exports.seed = function (knex) {

  const pokemon = [
    {
      name: "bulbasaur",
      type1: "grass",
      type2: "poison",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/1.png",
      number: 1,
      height: 7,
      weight: 69,
      entry: "A strange seed was planted on its back at birth. The plant sprouts and grows with this POKéMON.",
      habitat: "grassland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "ivysaur",
      type1: "grass",
      type2: "poison",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/2.png",
      number: 2,
      height: 10,
      weight: 130,
      entry: "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.",
      habitat: "grassland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "venusaur",
      type1: "grass",
      type2: "poison",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/3.png",
      number: 3,
      height: 6,
      weight: 85,
      entry: "The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.",
      habitat: "grassland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "charmander",
      type1: "fire",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/4.png",
      number: 4,
      height: 7,
      weight: 69,
      entry: "Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.",
      habitat: "mountain",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "charmeleon",
      type1: "fire",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/5.png",
      number: 5,
      height: 11,
      weight: 190,
      entry: "When it swings its burning tail, it elevates the temperature to unbearably high levels.",
      habitat: "mountain",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "charizard",
      type1: "fire",
      type2: "flying",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/6.png",
      number: 6,
      height: 17,
      weight: 905,
      entry: "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.",
      habitat: "mountain",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "squirtle",
      type1: "water",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/7.png",
      number: 7,
      height: 5,
      weight: 90,
      entry: "Shoots water at prey while in the water. Withdraws into its shell when in danger.",
      habitat: "waters-edge",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "wartortle",
      type1: "water",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/8.png",
      number: 8,
      height: 10,
      weight: 225,
      entry: "When tapped, this POKéMON will pull in its head, but its tail will still stick out a little bit.",
      habitat: "waters-edge",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "blastoise",
      type1: "water",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/9.png",
      number: 9,
      height: 16,
      weight: 855,
      entry: "It deliberately makes itself heavy so it can with­ stand the recoil of the water jets it fires.",
      habitat: "waters-edge",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "caterpie",
      type1: "bug",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/10.png",
      number: 10,
      height: 3,
      weight: 29,
      entry: "It releases a stench from its red antenna to repel enemies. It grows by molting repeatedly.",
      habitat: "forest",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "metapod",
      type1: "bug",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/11.png",
      number: 11,
      height: 3,
      weight: 29,
      entry: "This POKéMON is vulnerable to attack while its shell is soft, exposing its weak and tender body.",
      habitat: "forest",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "butterfree",
      type1: "bug",
      type2: "flying",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/12.png",
      number: 12,
      height: 11,
      weight: 320,
      entry: "In battle, it flaps its wings at high speed to release highly toxic dust into the air.",
      habitat: "forest",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "weedle",
      type1: "bug",
      type2: "poison",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/13.png",
      number: 13,
      height: 3,
      weight: 32,
      entry: "Often found in forests, eating leaves. It has a sharp venomous stinger on its head.",
      habitat: "forest",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "kakuna",
      type1: "bug",
      type2: "poison",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/14.png",
      number: 14,
      height: 6,
      weight: 100,
      entry: "Almost incapable of moving, this POKéMON can only harden its shell to protect itself from predators.",
      habitat: "forest",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "beedrill",
      type1: "bug",
      type2: "poison",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/15.png",
      number: 15,
      height: 10,
      weight: 295,
      entry: "Flies at high speed and attacks using its large venomous stingers on its forelegs and tail.",
      habitat: "forest",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "pidgey",
      type1: "normal",
      type2: "flying",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/16.png",
      number: 16,
      height: 3,
      weight: 18,
      entry: "A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.",
      habitat: "forest",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "pidgeotto",
      type1: "normal",
      type2: "flying",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/17.png",
      number: 17,
      height: 11,
      weight: 300,
      entry: "Very protective of its sprawling territorial area, this POKéMON will fiercely peck at any intruder.",
      habitat: "forest",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "pidgeot",
      type1: "normal",
      type2: "flying",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/18.png",
      number: 18,
      height: 15,
      weight: 395,
      entry: "When hunting, it skims the surface of water at high speed to pick off unwary prey such as MAGIKARP.",
      habitat: "forest",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "rattata",
      type1: "normal",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/19.png",
      number: 19,
      height: 3,
      weight: 35,
      entry: "Bites anything when it attacks. Small and very quick, it is a common sight in many places.",
      habitat: "grassland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "raticate",
      type1: "normal",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/20.png",
      number: 20,
      height: 7,
      weight: 185,
      entry: "It uses its whis­kers to maintain its balance. It apparently slows down if they are cut off.",
      habitat: "grassland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "spearow",
      type1: "normal",
      type2: "flying",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/21.png",
      number: 21,
      height: 3,
      weight: 20,
      entry: "Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne",
      habitat: "rough-terrain",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "fearow",
      type1: "normal",
      type2: "flying",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/22.png",
      number: 22,
      height: 12,
      weight: 380,
      entry: "With its huge and magnificent wings, it can keep aloft without ever having to land for rest.",
      habitat: "rough-terrain",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "ekans",
      type1: "poison",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/23.png",
      number: 23,
      height: 20,
      weight: 69,
      entry: "Moves silently and stealthily. Eats the eggs of birds, such as PIDGEY and SPEAROW, whole.",
      habitat: "grassland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "arbok",
      type1: "poison",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/24.png",
      number: 24,
      height: 35,
      weight: 650,
      entry: "It is rumored that the ferocious warning markings on its belly differ from area to area.",
      habitat: "grassland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "pikachu",
      type1: "electric",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/25.png",
      number: 25,
      height: 4,
      weight: 60,
      entry: "When several of these POKéMON gather, their electricity could build and cause lightning storms.",
      habitat: "forest",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "raichu",
      type1: "electric",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/26.png",
      number: 26,
      height: 8,
      weight: 300,
      entry: "Its tail discharges electricity into the ground, protecting it from getting shocked.",
      habitat: "forest",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "sandshrew",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/27.png",
      number: 27,
      height: 6,
      weight: 120,
      entry: "Burrows deep underground in arid locations far from water. It only emerges to hunt for food.",
      habitat: "rough-terrain",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "sandslash",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/28.png",
      number: 28,
      height: 10,
      weight: 295,
      entry: "Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape.",
      habitat: "rough-terrain",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "nidoran ♀",
      type1: "poison",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/29.png",
      number: 29,
      height: 4,
      weight: 70,
      entry: "Although small, its venomous barbs render this POKéMON dangerous. The female has smaller horns.",
      habitat: "grassland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "nidorina",
      type1: "poison",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/30.png",
      number: 30,
      height: 8,
      weight: 200,
      entry: "The female's horn develops slowly. Prefers physical attacks such as clawing and biting.",
      habitat: "grassland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "nidoqueen",
      type1: "poison",
      type2: "ground",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/31.png",
      number: 31,
      height: 13,
      weight: 600,
      entry: "Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves.",
      habitat: "grassland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "nidoran ♂",
      type1: "poison",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/32.png",
      number: 32,
      height: 5,
      weight: 90,
      entry: "Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom",
      habitat: "grassland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "nidorino",
      type1: "poison",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/33.png",
      number: 33,
      height: 9,
      weight: 195,
      entry: "An aggressive POKéMON that is quick to attack. The horn on its head secretes a powerful venom.",
      habitat: "grassland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "nidoking",
      type1: "poison",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/34.png",
      number: 34,
      height: 14,
      weight: 620,
      entry: "One swing of its mighty tail can snap a telephone pole as if it were a matchstick.",
      habitat: "grassland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "clefairy",
      type1: "fairy",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/35.png",
      number: 35,
      height: 6,
      weight: 75,
      entry: "Its magical and cute appeal has many admirers. It is rare and found only in certain areas.",
      habitat: "mountain",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "clefable",
      type1: "fairy",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/36.png",
      number: 36,
      height: 13,
      weight: 400,
      entry: "A timid fairy POKéMON that is rarely seen. It will run and hide the moment it senses people.",
      habitat: "mountain",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "vulpix",
      type1: "fire",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/37.png",
      number: 37,
      height: 6,
      weight: 99,
      entry: "At the time of birth, it has just one tail. The tail splits from its tip as it grows older.",
      habitat: "grassland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "ninetales",
      type1: "fire",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/38.png",
      number: 38,
      height: 11,
      weight: 199,
      entry: "Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse.",
      habitat: "grassland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "jigglypuff",
      type1: "normal",
      type2: "fairy",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/39.png",
      number: 39,
      height: 5,
      weight: 55,
      entry: "When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.",
      habitat: "grassland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "wigglytuff",
      type1: "normal",
      type2: "fairy",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/40.png",
      number: 40,
      height: 10,
      weight: 120,
      entry: "The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size.",
      habitat: "grassland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "zubat",
      type1: "poison",
      type2: "flying",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/41.png",
      number: 41,
      height: 8,
      weight: 75,
      entry: "Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "golbat",
      type1: "poison",
      type2: "flying",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/42.png",
      number: 42,
      height: 16,
      weight: 550,
      entry: "Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "oddish",
      type1: "grass",
      type2: "poison",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/43.png",
      number: 43,
      height: 5,
      weight: 54,
      entry: "During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds.",
      habitat: "grassland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "gloom",
      type1: "grass",
      type2: "poison",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/44.png",
      number: 44,
      height: 8,
      weight: 86,
      entry: "It secretes a sticky, drool-like honey. Although sweet, it smells too repulsive to get very close.",
      habitat: "grassland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "vileplume",
      type1: "grass",
      type2: "poison",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/45.png",
      number: 45,
      height: 12,
      weight: 186,
      entry: "It has the world's largest petals. With every step, the petals shake out heavy clouds of toxic pollen.",
      habitat: "grassland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "paras",
      type1: "bug",
      type2: "grass",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/46.png",
      number: 46,
      height: 3,
      weight: 54,
      entry: "Burrows to suck tree roots. The mushrooms on its back grow by draw­ing nutrients from the bug host.",
      habitat: "forest",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "parasect",
      type1: "bug",
      type2: "grass",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/47.png",
      number: 47,
      height: 10,
      weight: 295,
      entry: "A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places.",
      habitat: "forest",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "venonat",
      type1: "bug",
      type2: "poison",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/48.png",
      number: 48,
      height: 10,
      weight: 300,
      entry: "Lives in the shadows of tall trees where it eats insects. It is attracted by light at night.",
      habitat: "forest",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "venomoth",
      type1: "bug",
      type2: "poison",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/49.png",
      number: 49,
      height: 15,
      weight: 125,
      entry: "The dust-like scales covering its wings are color coded to indicate the kinds of poison it has.",
      habitat: "forest",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "dugtrio",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/51.png",
      number: 51,
      height: 7,
      weight: 333,
      entry: "A team of diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "meowth",
      type1: "normal",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/52.png",
      number: 52,
      height: 4,
      weight: 42,
      entry: "Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change.",
      habitat: "urban",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "persian",
      type1: "normal",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/53.png",
      number: 53,
      height: 10,
      weight: 320,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "psyduck",
      type1: "water",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/54.png",
      number: 54,
      height: 8,
      weight: 196,
      entry: "While lulling its enemies with its vacant look, this wily POKéMON will use psychokinetic powers",
      habitat: "waters-edge",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "golduck",
      type1: "water",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/55.png",
      number: 55,
      height: 17,
      weight: 766,
      entry: "Often seen swim­ming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa.",
      habitat: "waters-edge",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "mankey",
      type1: "fighting",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/56.png",
      number: 56,
      height: 5,
      weight: 280,
      entry: "Extremely quick to anger. It could be docile one moment then thrashing away the next instant.",
      habitat: "mountain",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "primeape",
      type1: "fighting",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/57.png",
      number: 57,
      height: 10,
      weight: 320,
      entry: "Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught.",
      habitat: "mountain",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "growlithe",
      type1: "fire",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/58.png",
      number: 58,
      height: 7,
      weight: 190,
      entry: "Very protective of its territory. It will bark and bite to repel intruders from its space.",
      habitat: "grasland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "arcanine",
      type1: "fire",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/59.png",
      number: 59,
      height: 19,
      weight: 1550,
      entry: "A POKéMON that has been admired since the past for its beauty. It runs agilely as if on wings.",
      habitat: "grassland",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "poliwag",
      type1: "water",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/60.png",
      number: 60,
      height: 6,
      weight: 124,
      entry: "Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand.",
      habitat: "waters-edge",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "poliwhirl",
      type1: "water",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/61.png",
      number: 61,
      height: 10,
      weight: 200,
      entry: "Capable of living in or out of water. When out of water, it sweats to keep its body slimy.",
      habitat: "waters-edge",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "poliwrath",
      type1: "water",
      type2: "fighting",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/62.png",
      number: 62,
      height: 13,
      weight: 540,
      entry: "An adept swimmer at both the front crawl and breast stroke. Easily overtakes the best human swimmers.",
      habitat: "waters-edge",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "abra",
      type1: "psychic",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/63.png",
      number: 63,
      height: 9,
      weight: 195,
      entry: "Using its ability to read minds, it will identify impending danger and teleport to safety.",
      habitat: "urban",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "kadabra",
      type1: "psychic",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/64.png",
      number: 64,
      height: 13,
      weight: 565,
      entry: "It emits special alpha waves from its body that induce headaches just by being close by.",
      habitat: "urban",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "alakazam",
      type1: "psychic",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/65.png",
      number: 65,
      height: 15,
      weight: 480,
      entry: "Its brain can out­ perform a super­ computer. Its IQ is said to be 5,000.",
      habitat: "urban",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "machop",
      type1: "fighting",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/66.png",
      number: 66,
      height: 8,
      weight: 195,
      entry: "Loves to build its muscles. It trains in all styles of martial arts to become even stronger",
      habitat: "mountain",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "machoke",
      type1: "fighting",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/67.png",
      number: 67,
      height: 15,
      weight: 705,
      entry: "Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions.",
      habitat: "mountain",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "machamp",
      type1: "fighting",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/68.png",
      number: 68,
      height: 16,
      weight: 1300,
      entry: "Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon.",
      habitat: "mountain",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "bellsprout",
      type1: "grass",
      type2: "poison",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/69.png",
      number: 69,
      height: 7,
      weight: 40,
      entry: "Even though its body is extremely skinny, it is blindingly fast when catching its prey.",
      habitat: "forest",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "weepinbell",
      type1: "grass",
      type2: "poison",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/70.png",
      number: 70,
      height: 10,
      weight: 64,
      entry: "It spits out poison powder to immobilize the enemy and then finishes it with a spray of acid",
      habitat: "forest",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "victreebel",
      type1: "grass",
      type2: "poison",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/71.png",
      number: 71,
      height: 17,
      weight: 155,
      entry: "Said to live in huge colonies deep in jungles, although no one has ever returned from there.",
      habitat: "forest",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "tentacool",
      type1: "water",
      type2: "poison",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/72.png",
      number: 72,
      height: 9,
      weight: 455,
      entry: "Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid.",
      habitat: "sea",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "tentacruel",
      type1: "water",
      type2: "poison",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/73.png",
      number: 73,
      height: 16,
      weight: 550,
      entry: "The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey.",
      habitat: "sea",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "geodude",
      type1: "rock",
      type2: "ground",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/74.png",
      number: 74,
      height: 4,
      weight: 200,
      entry: "Found in fields and mountains. Mistaking them for boulders, people often step or trip on them.",
      habitat: "mountain",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "graveler",
      type1: "rock",
      type2: "ground",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/75.png",
      number: 75,
      height: 10,
      weight: 1050,
      entry: "Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction.",
      habitat: "mountain",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "golem",
      type1: "rock",
      type2: "ground",
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/76.png",
      number: 76,
      height: 14,
      weight: 3000,
      entry: "Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage.",
      habitat: "mountain",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    {
      name: "diglett",
      type1: "ground",
      type2: null,
      imgURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png",
      number: 50,
      height: 2,
      weight: 8,
      entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
      habitat: "cave",
      legendary: false, 
      mythical: false,
      ancient: false
    },
    
  ]

  return knex("pokemon").insert(pokemon)
}