DROP TABLE IF EXISTS team_members;

CREATE TABLE team_members (
    pokemon_Id INTEGER REFERENCES pokemon(id) ON DELETE CASCADE,
    team_Id INTEGER REFERENCES teams(id) ON DELETE CASCADE ON UPDATE CASCADE,
    nickname VARCHAR(255) DEFAULT NULL
);