--
-- PostgreSQL database dump
--

-- Dumped from database version 13.1
-- Dumped by pg_dump version 13.1

-- Started on 2021-02-05 22:15:42

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 207 (class 1259 OID 34362)
-- Name: pokemon; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pokemon (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    type1 character varying(255) NOT NULL,
    type2 character varying(255),
    "imgURL" character varying(255) NOT NULL,
    number integer NOT NULL,
    height integer NOT NULL,
    weight integer NOT NULL,
    entry character varying(255) NOT NULL,
    habitat character varying(255) NOT NULL,
    legendary boolean,
    mythical boolean,
    ancient boolean,
    region character varying(255) NOT NULL,
    "modern_imgURL" character varying(255) NOT NULL,
    "shiny_imgURL" character varying(255) NOT NULL
);


ALTER TABLE public.pokemon OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 34360)
-- Name: pokemon_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.pokemon_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.pokemon_id_seq OWNER TO postgres;

--
-- TOC entry 3031 (class 0 OID 0)
-- Dependencies: 206
-- Name: pokemon_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.pokemon_id_seq OWNED BY public.pokemon.id;


--
-- TOC entry 2879 (class 2604 OID 34365)
-- Name: pokemon id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pokemon ALTER COLUMN id SET DEFAULT nextval('public.pokemon_id_seq'::regclass);


--
-- TOC entry 3025 (class 0 OID 34362)
-- Dependencies: 207
-- Data for Name: pokemon; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pokemon (id, name, type1, type2, "imgURL", number, height, weight, entry, habitat, legendary, mythical, ancient, region, "modern_imgURL", "shiny_imgURL") FROM stdin;
1	bulbasaur	grass	poison	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/1.png	1	7	69	A strange seed was planted on its back at birth. The plant sprouts and grows with this POKéMON.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/1.png
2	ivysaur	grass	poison	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/2.png	2	10	130	When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/2.png
3	venusaur	grass	poison	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/3.png	3	6	85	The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/3.png
4	charmander	fire	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/4.png	4	7	69	Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.	mountain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/4.png
5	charmeleon	fire	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/5.png	5	11	190	When it swings its burning tail, it elevates the temperature to unbearably high levels.	mountain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/5.png
6	charizard	fire	flying	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/6.png	6	17	905	Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.	mountain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/6.png
7	squirtle	water	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/7.png	7	5	90	Shoots water at prey while in the water. Withdraws into its shell when in danger.	waters-edge	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/7.png
8	wartortle	water	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/8.png	8	10	225	When tapped, this POKéMON will pull in its head, but its tail will still stick out a little bit.	waters-edge	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/8.png
9	blastoise	water	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/9.png	9	16	855	It deliberately makes itself heavy so it can with­ stand the recoil of the water jets it fires.	waters-edge	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/9.png
10	caterpie	bug	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/10.png	10	3	29	It releases a stench from its red antenna to repel enemies. It grows by molting repeatedly.	forest	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10.png
11	metapod	bug	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/11.png	11	3	29	This POKéMON is vulnerable to attack while its shell is soft, exposing its weak and tender body.	forest	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/11.png
12	butterfree	bug	flying	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/12.png	12	11	320	In battle, it flaps its wings at high speed to release highly toxic dust into the air.	forest	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/12.png
13	weedle	bug	poison	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/13.png	13	3	32	Often found in forests, eating leaves. It has a sharp venomous stinger on its head.	forest	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/13.png
14	kakuna	bug	poison	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/14.png	14	6	100	Almost incapable of moving, this POKéMON can only harden its shell to protect itself from predators.	forest	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/14.png
15	beedrill	bug	poison	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/15.png	15	10	295	Flies at high speed and attacks using its large venomous stingers on its forelegs and tail.	forest	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/15.png
16	pidgey	normal	flying	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/16.png	16	3	18	A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.	forest	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/16.png
17	pidgeotto	normal	flying	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/17.png	17	11	300	Very protective of its sprawling territorial area, this POKéMON will fiercely peck at any intruder.	forest	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/17.png
18	pidgeot	normal	flying	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/18.png	18	15	395	When hunting, it skims the surface of water at high speed to pick off unwary prey such as MAGIKARP.	forest	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/18.png
19	rattata	normal	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/19.png	19	3	35	Bites anything when it attacks. Small and very quick, it is a common sight in many places.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/19.png
20	raticate	normal	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/20.png	20	7	185	It uses its whis­kers to maintain its balance. It apparently slows down if they are cut off.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/20.png
21	spearow	normal	flying	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/21.png	21	3	20	Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne	rough-terrain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/21.png
22	fearow	normal	flying	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/22.png	22	12	380	With its huge and magnificent wings, it can keep aloft without ever having to land for rest.	rough-terrain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/22.png
23	ekans	poison	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/23.png	23	20	69	Moves silently and stealthily. Eats the eggs of birds, such as PIDGEY and SPEAROW, whole.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/23.png
24	arbok	poison	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/24.png	24	35	650	It is rumored that the ferocious warning markings on its belly differ from area to area.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/24.png
25	pikachu	electric	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/25.png	25	4	60	When several of these POKéMON gather, their electricity could build and cause lightning storms.	forest	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/25.png
26	raichu	electric	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/26.png	26	8	300	Its tail discharges electricity into the ground, protecting it from getting shocked.	forest	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/26.png
27	sandshrew	ground	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/27.png	27	6	120	Burrows deep underground in arid locations far from water. It only emerges to hunt for food.	rough-terrain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/27.png
28	sandslash	ground	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/28.png	28	10	295	Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape.	rough-terrain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/28.png
29	nidoran ♀	poison	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/29.png	29	4	70	Although small, its venomous barbs render this POKéMON dangerous. The female has smaller horns.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/29.png
30	nidorina	poison	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/30.png	30	8	200	The female's horn develops slowly. Prefers physical attacks such as clawing and biting.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/30.png
31	nidoqueen	poison	ground	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/31.png	31	13	600	Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/31.png
32	nidoran ♂	poison	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/32.png	32	5	90	Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/32.png
33	nidorino	poison	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/33.png	33	9	195	An aggressive POKéMON that is quick to attack. The horn on its head secretes a powerful venom.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/33.png
34	nidoking	poison	ground	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/34.png	34	14	620	One swing of its mighty tail can snap a telephone pole as if it were a matchstick.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/34.png
35	clefairy	fairy	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/35.png	35	6	75	Its magical and cute appeal has many admirers. It is rare and found only in certain areas.	mountain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/35.png
36	clefable	fairy	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/36.png	36	13	400	A timid fairy POKéMON that is rarely seen. It will run and hide the moment it senses people.	mountain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/36.png
37	vulpix	fire	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/37.png	37	6	99	At the time of birth, it has just one tail. The tail splits from its tip as it grows older.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/37.png
38	ninetales	fire	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/38.png	38	11	199	Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/38.png
39	jigglypuff	normal	fairy	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/39.png	39	5	55	When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/39.png
40	wigglytuff	normal	fairy	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/40.png	40	10	120	The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/40.png
41	zubat	poison	flying	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/41.png	41	8	75	Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.	cave	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/41.png
42	golbat	poison	flying	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/42.png	42	16	550	Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly.	cave	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/42.png
43	oddish	grass	poison	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/43.png	43	5	54	During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/43.png
44	gloom	grass	poison	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/44.png	44	8	86	It secretes a sticky, drool-like honey. Although sweet, it smells too repulsive to get very close.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/44.png
45	vileplume	grass	poison	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/45.png	45	12	186	It has the world's largest petals. With every step, the petals shake out heavy clouds of toxic pollen.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/45.png
46	paras	bug	grass	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/46.png	46	3	54	Burrows to suck tree roots. The mushrooms on its back grow by draw­ing nutrients from the bug host.	forest	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/46.png
47	parasect	bug	grass	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/47.png	47	10	295	A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places.	forest	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/47.png
48	venonat	bug	poison	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/48.png	48	10	300	Lives in the shadows of tall trees where it eats insects. It is attracted by light at night.	forest	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/48.png
49	venomoth	bug	poison	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/49.png	49	15	125	The dust-like scales covering its wings are color coded to indicate the kinds of poison it has.	forest	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/49.png
50	diglett	ground	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/50.png	50	2	8	Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.	cave	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/50.png
51	dugtrio	ground	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/51.png	51	7	333	A team of diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground.	cave	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/51.png
52	meowth	normal	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/52.png	52	4	42	Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/52.png
53	persian	normal	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/53.png	53	10	320	Although its fur has many admirers, it is tough to fraise as a pet because of its fickle meanness.	cave	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/53.png
54	psyduck	water	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/54.png	54	8	196	While lulling its enemies with its vacant look, this wily POKéMON will use psychokinetic powers	waters-edge	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/54.png
55	golduck	water	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/55.png	55	17	766	Often seen swim­ming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa.	waters-edge	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/55.png
56	mankey	fighting	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/56.png	56	5	280	Extremely quick to anger. It could be docile one moment then thrashing away the next instant.	mountain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/56.png
57	primeape	fighting	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/57.png	57	10	320	Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught.	mountain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/57.png
58	growlithe	fire	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/58.png	58	7	190	Very protective of its territory. It will bark and bite to repel intruders from its space.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/58.png
59	arcanine	fire	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/59.png	59	19	1550	A POKéMON that has been admired since the past for its beauty. It runs agilely as if on wings.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/59.png
60	poliwag	water	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/60.png	60	6	124	Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand.	waters-edge	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/60.png
61	poliwhirl	water	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/61.png	61	10	200	Capable of living in or out of water. When out of water, it sweats to keep its body slimy.	waters-edge	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/61.png
62	poliwrath	water	fighting	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/62.png	62	13	540	An adept swimmer at both the front crawl and breast stroke. Easily overtakes the best human swimmers.	waters-edge	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/62.png
63	abra	psychic	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/63.png	63	9	195	Using its ability to read minds, it will identify impending danger and teleport to safety.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/63.png
64	kadabra	psychic	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/64.png	64	13	565	It emits special alpha waves from its body that induce headaches just by being close by.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/64.png
65	alakazam	psychic	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/65.png	65	15	480	Its brain can out­ perform a super­ computer. Its IQ is said to be 5,000.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/65.png
66	machop	fighting	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/66.png	66	8	195	Loves to build its muscles. It trains in all styles of martial arts to become even stronger	mountain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/66.png
67	machoke	fighting	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/67.png	67	15	705	Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions.	mountain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/67.png
68	machamp	fighting	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/68.png	68	16	1300	Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon.	mountain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/68.png
69	bellsprout	grass	poison	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/69.png	69	7	40	Even though its body is extremely skinny, it is blindingly fast when catching its prey.	forest	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/69.png
70	weepinbell	grass	poison	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/70.png	70	10	64	It spits out poison powder to immobilize the enemy and then finishes it with a spray of acid	forest	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/70.png
71	victreebel	grass	poison	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/71.png	71	17	155	Said to live in huge colonies deep in jungles, although no one has ever returned from there.	forest	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/71.png
72	tentacool	water	poison	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/72.png	72	9	455	Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid.	sea	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/72.png
73	tentacruel	water	poison	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/73.png	73	16	550	The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey.	sea	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/73.png
74	geodude	rock	ground	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/74.png	74	4	200	Found in fields and mountains. Mistaking them for boulders, people often step or trip on them.	mountain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/74.png
75	graveler	rock	ground	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/75.png	75	10	1050	Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction.	mountain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/75.png
76	golem	rock	ground	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/76.png	76	14	3000	Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage.	mountain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/76.png
77	ponyta	fire	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/77.png	77	10	300	Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/77.png
78	rapidash	fire	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/78.png	78	17	950	Very competitive, this POKéMON will chase anything that moves fast in the hopes of racing it.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/78.png
79	slowpoke	water	psychic	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/79.png	79	12	360	Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack.	waters-edge	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/79.png
80	slowbro	water	psychic	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/80.png	80	16	785	The shellder that is latched onto SLOWPOKE's tail is said to feed on the host's left-over scraps.	waters-edge	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/80.png
81	magnemite	electric	steel	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/81.png	81	3	60	Uses anti-gravity to stay suspended. Appears without warning and paralyzes its prey.	rough-terrain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/81.png
82	magneton	electric	steel	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/82.png	82	10	600	Formed by several magnemites linked together. They frequently appear when sunspots flare up.	rough-terrain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/82.png
83	farfetch'd	normal	flying	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/83.png	83	8	150	The sprig of green onions it holds is its weapon. It is used much like a metal sword.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/83.png
84	doduo	normal	flying	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/84.png	84	14	392	A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/84.png
85	dodrio	normal	flying	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/85.png	85	18	852	Uses its three brains to execute complex plans. While two heads sleep, one head stays awake.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/85.png
86	seel	water	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/86.png	86	11	900	The protruding horn on its head is very hard. It is used for bashing through thick ice.	sea	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/86.png
87	dewgong	water	ice	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/87.png	87	17	1200	Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters.	sea	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/87.png
88	grimer	poison	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/88.png	88	9	300	Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/88.png
89	muk	poison	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/89.png	89	12	300	Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/89.png
90	shellder	water	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/90.png	90	3	40	Its hard shell repels any kind of attack. It is vulnerable only when its shell is open.	sea	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/90.png
91	cloyster	water	ice	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/91.png	91	15	1325	Cloyster that live in seas with harsh tidal currents grow large, sharp spikes on their shells.	sea	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/91.png
92	gastly	ghost	poison	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/92.png	92	13	1	Almost invisible, this gaseous POKéMON cloaks the target and puts it to sleep without notice.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/92.png
93	haunter	ghost	poison	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/93.png	93	16	1	Because of its ability to slip through block walls, it is said to be from an­other dimension.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/93.png
94	gengar	ghost	poison	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/94.png	94	15	405	Under a full moon, this POKéMON likes to mimic the shadows of people and laugh at their fright.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/94.png
95	onix	rock	ground	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/95.png	95	88	2100	As it grows, the stone portions of its body harden to become similar to a diamond, but colored black.	cave	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/95.png
96	drowzee	psychic	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/96.png	96	10	324	Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/96.png
97	hypno	psychic	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/97.png	97	16	756	The arcing movement and glitter of the pendulum lull the foe into a deep state of hypnosis. While this POKéMON searches for prey,it polishes the pendulum.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/97.png
98	krabby	water	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/98.png	98	4	65	Its pincers are not only powerful weapons, they are used for balance when walking sideways.	waters-edge	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/98.png
99	kingler	water	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/99.png	99	13	600	The large pincer has 10000 hp of crushing power. However, its huge size makes it unwieldy to use.	waters-edge	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/99.png
100	voltorb	electric	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/100.png	100	5	104	Usually found in power plants. Easily mistaken for a POKé BALL, they have zapped many people.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/100.png
101	electrode	electric	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/101.png	101	12	666	It stores electric energy under very high pressure. It often explodes with little or no provocation.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/101.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/101.png
102	exeggcute	grass	psychic	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/102.png	102	4	25	Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms.	forest	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/102.png
103	exeggutor	grass	psychic	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/103.png	103	20	1200	Legend has it that on rare occasions, one of its heads will drop off and continue on as an exeggcute.	forest	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/103.png
104	cubone	ground	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/104.png	104	4	65	Wears the skull of its deceased mother. Its cries echo inside the skull and come out as a sad melody.	mountain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/104.png
105	marowak	ground	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/105.png	105	10	450	The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets.	mountain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/105.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/105.png
106	hitmonlee	fighting	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/106.png	106	15	498	When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/106.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/106.png
107	hitmonchan	fighting	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/107.png	107	14	502	While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/107.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/107.png
108	lickitung	normal	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/108.png	108	12	655	Its tongue can be extended like a chameleon's. It leaves a tingling sensation when it licks enemies.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/108.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/108.png
109	koffing	poison	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/109.png	109	6	10	Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/109.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/109.png
110	weezing	poison	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/110.png	110	12	95	It lives and grows by absorbing dust, germs and poison gases that are contained in toxic waste and garbage.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/110.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/110.png
111	rhyhorn	ground	rock	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/111.png	111	10	1150	Its massive bones are 1000 times harder than human bones. It can easily knock a trailer flying.	rough-terrain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/111.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/111.png
112	rhydon	ground	rock	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/112.png	112	19	1200	Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees.	rough-terrain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/112.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/112.png
113	chansey	normal	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/113.png	113	11	346	A rare and elusive POKéMON that is said to bring happiness to those who manage to get it.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/113.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/113.png
114	tangela	grass	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/114.png	114	10	350	The whole body is swathed with wide vines that are similar to sea­weed. Its vines shake as it walks.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/114.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/114.png
115	kangaskhan	normal	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/115.png	115	22	800	The infant rarely ventures out of its mother's protective pouch until it is 3 years old.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/115.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/115.png
116	horsea	water	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/116.png	116	4	80	Known to shoot down flying bugs with precision blasts of ink from the surface of the water.	sea	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/116.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/116.png
117	seadra	water	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/117.png	117	12	250	Capable of swim­ming backwards by rapidly flapping its wing-like pectoral fins and stout tail.	sea	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/117.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/117.png
118	goldeen	water	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/118.png	118	6	150	Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen.	sea	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/118.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/118.png
119	seaking	water	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/119.png	119	13	390	In the autumn spawning season, they can be seen swimming power­ fully up rivers and creeks.	sea	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/119.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/119.png
120	staryu	water	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/120.png	120	8	345	An enigmatic POKéMON that can effortlessly regenerate any appendage it loses in battle.	sea	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/120.png
121	starmie	water	psychic	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/121.png	121	11	800	Its central core glows with the seven colors of the rainbow. Some people value the core as a gem.	sea	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/121.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/121.png
122	mr. mime	psychic	fairy	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/122.png	122	13	545	If interrupted while it is miming, it will slap around the offender with its broad hands.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/122.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/122.png
123	scyther	bug	flying	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/123.png	123	15	560	With ninja-like agility and speed, it can create the illusion that there is more than one.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/123.png
124	jynx	ice	psychic	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/124.png	124	14	406	Its cries sound like human speech. However, it is impossible to tell what it is trying to say.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/124.png
125	electabuzz	electric	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/125.png	125	11	300	Normally found near power plants, they can wander away and cause major blackouts in cities.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/125.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/125.png
126	magmar	fire	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/126.png	126	13	445	Its body always burns with an orange glow that enables it to hide perfectly among flames.	mountain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/126.png
127	pinsir	bug	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/127.png	127	15	550	If it fails to crush the victim in its pincers, it will swing it around and toss it hard.	forest	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/127.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/127.png
128	tauros	normal	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/128.png	128	14	884	When it targets an enemy, it charges furiously while whipping its body with its long tails.	grassland	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/128.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/128.png
129	magikarp	water	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/129.png	129	9	100	In the distant past, it was somewhat stronger than the horribly weak descendants that exist today.	waters-edge	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/129.png
130	gyarados	water	flying	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/130.png	130	65	2350	Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage.	waters-edge	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/130.png
131	lapras	water	ice	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/131.png	131	25	2200	A POKéMON that has been over­ hunted almost to extinction. It can ferry people across the water.	sea	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/131.png
132	ditto	normal	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/132.png	132	3	40	It can freely recombine its own cellular structure to transform into other life-forms.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/132.png
133	eevee	normal	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/133.png	133	3	65	Its genetic code is irregular. It may mutate if it is exposed to radiation from element stones.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/133.png
134	vaporeon	water	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/134.png	134	10	290	Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaid's.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/134.png
135	jolteon	electric	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/135.png	135	8	245	It accumulates negative ions in the atmosphere to blast out 10000-volt lightning bolts.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/135.png
136	flareon	fire	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/136.png	136	9	250	When storing thermal energy in its body, its temperature could soar to over 1600 C.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/136.png
137	porygon	normal	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/137.png	137	8	365	A POKéMON that consists entirely of programming code. Capable of moving freely in cyberspace.	urban	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/137.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/137.png
138	omanyte	rock	water	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/138.png	138	4	75	Although long extinct, in rare cases, it can be genetically resurrected from fossils.	sea	f	f	t	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/138.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/138.png
139	omastar	rock	water	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/139.png	139	10	350	Once wrapped around its prey, it never lets go. It eats the prey by tearing at it with sharp fangs.	sea	f	f	t	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/139.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/139.png
140	kabuto	rock	water	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/140.png	140	5	115	A POKéMON that was resurrected from a fossil found in what was once the ocean floor eons ago.	sea	f	f	t	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/140.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/140.png
141	kabutops	rock	water	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/141.png	141	13	405	Its sleek shape is perfect for swim­ming. It slashes prey with its claws and drains the body fluids.	sea	f	f	t	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/141.png
142	aerodactyl	rock	flying	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/142.png	142	18	590	A ferocious, pre­historic POKéMON that goes for the enemy's throat with its serrated saw-like fangs.	mountain	f	f	t	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/142.png
143	snorlax	normal	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/143.png	143	21	4600	Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful.	mountain	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/143.png
144	articuno	ice	flying	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/144.png	144	17	554	A legendary bird POKéMON that is said to appear to doomed people who are lost in icy mountains.	unknown	t	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/144.png
145	zapdos	electric	flying	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/145.png	145	16	526	A legendary bird POKéMON that is said to appear from clouds while dropping enormous lightning bolts.	unknown	t	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/145.png
146	moltres	fire	flying	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/146.png	146	20	600	It is said to be the legendary bird Pokémon of fire. Every flap of its wings creates a dazzling flare of flames.	unknown	t	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/146.png
147	dratini	dragon	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/147.png	147	18	33	Long considered a mythical POKéMON until recently when a small colony was found living underwater.	waters-edge	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/147.png
148	dragonair	dragon	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/148.png	148	40	165	A mystical POKéMON that exudes a gentle aura. Has the ability to change climate conditions.	waters-edge	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/148.png
149	dragonite	dragon	flying	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/149.png	149	22	2100	An extremely rarely seen marine POKéMON. Its intelligence is said to match that of humans.	waters-edge	f	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/149.png
150	mewtwo	psychic	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/150.png	150	20	1220	It was created by a scientist after years of horrific gene splicing and DNA engineering experiments.	unknown	t	f	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/150.png
151	mew	psychic	\N	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/151.png	151	4	40	So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide.	unknown	f	t	f	kanto	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png	https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/151.png
\.


--
-- TOC entry 3032 (class 0 OID 0)
-- Dependencies: 206
-- Name: pokemon_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pokemon_id_seq', 151, true);


--
-- TOC entry 2881 (class 2606 OID 34378)
-- Name: pokemon pokemon_entry_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pokemon
    ADD CONSTRAINT pokemon_entry_unique UNIQUE (entry);


--
-- TOC entry 2883 (class 2606 OID 34374)
-- Name: pokemon pokemon_imgurl_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pokemon
    ADD CONSTRAINT pokemon_imgurl_unique UNIQUE ("imgURL");


--
-- TOC entry 2885 (class 2606 OID 34380)
-- Name: pokemon pokemon_modern_imgurl_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pokemon
    ADD CONSTRAINT pokemon_modern_imgurl_unique UNIQUE ("modern_imgURL");


--
-- TOC entry 2887 (class 2606 OID 34372)
-- Name: pokemon pokemon_name_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pokemon
    ADD CONSTRAINT pokemon_name_unique UNIQUE (name);


--
-- TOC entry 2889 (class 2606 OID 34376)
-- Name: pokemon pokemon_number_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pokemon
    ADD CONSTRAINT pokemon_number_unique UNIQUE (number);


--
-- TOC entry 2891 (class 2606 OID 34370)
-- Name: pokemon pokemon_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pokemon
    ADD CONSTRAINT pokemon_pkey PRIMARY KEY (id);


--
-- TOC entry 2893 (class 2606 OID 34382)
-- Name: pokemon pokemon_shiny_imgurl_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pokemon
    ADD CONSTRAINT pokemon_shiny_imgurl_unique UNIQUE ("shiny_imgURL");


-- Completed on 2021-02-05 22:15:42

--
-- PostgreSQL database dump complete
--

